# Machine Learning
## Supervised Learning - Linear Regression

### Primero importamos las librerias necesarias

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

### Cargar el conjunto de datos (Dataset)
Carguemos el dataset y exploremos los datos

In [3]:
file_path = 'Automobile_price_data.csv'
df = pd.read_csv(file_path)
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
1,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
2,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
3,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
4,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.8,8.8,101,5800,23,29,16430

### Preparacion de los datos
Necesitamos limpiar los datos para que este preparados para el modelo de regresion.

In [ ]:
# Convert missing values and prepare the dataset
df = df.replace('?', pd.NA).dropna()
df['price'] = pd.to_numeric(df['price'])
df['horsepower'] = pd.to_numeric(df['horsepower'])

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
1,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
2,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
3,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
4,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.8,8.8,101,5800,23,29,16430

In [5]:
# Select features and target variable
# Split the data into features and target variable
X = df[['horsepower']]
y = df['price']

### Dividir la informacion
Dividimos la informacion en en datos de entrenamiento y datos de prueba

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Entrenar el modelo
Ahora entrenamois el modelo de regresion linear usando los datos de entrenemiento.

In [8]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

### Evaluar el modelo
Calcularemos el erro promedio al cuadrado (MSE) para evaluar el rendimiento del modelo.

In [10]:
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print(f'Mean Squared Error: {mse}')
print(f'Root Mean Squared Error: {rmse}')
print(f'R² Score: {r2}')

Mean Squared Error: 7431602.670900866
Root Mean Squared Error: 2726.0965997009107
R² Score: 0.5823682396698118

# Error Cuadrático Medio (RMSE): 2726.10

En promedio, las predicciones del modelo se desvían aproximadamente $2726.10 de los precios reales de los automóviles. 
El RMSE está en las mismas unidades que la variable objetivo (precio), lo que facilita su comprensión.

# Puntaje R²: 0.582

El modelo explica alrededor del 58.2% de la varianza en los precios de los automóviles.
Esto indica un nivel moderado de precisión en las predicciones del modelo.

## Interpretación:

- Las predicciones del modelo son algo precisas, pero se pueden mejorar. La característica de potencia no es suficiente para predecir el precio del automóvil.
- El error promedio de predicción es de aproximadamente $2726.10, lo que es moderado.
- El modelo captura el 58.2% de la variabilidad en los precios de los automóviles, pero aún hay margen para mejorar.

## Próximos Pasos:

- Mejorar el modelo refinando las características y probando diferentes modelos:
  - Usar un **Random Forest Regressor**.
  - Realizar **Regresión Lineal Múltiple** con **Random Forest Regressor**.

- Ajustar la configuración del modelo para reducir los errores.

- Asegurarse de que los datos estén limpios y bien preparados, y manejar cualquier valor atípico o puntos de datos inusuales.